name: ami register action
on : 
  push:
    branches:
      - main
jobs: 
  ami-register:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${AWS_ACCESS_KEY_ID}
    - run: export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - run: export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - uses: actions/checkout@master
      name: Checkout

    - uses: hashicorp/packer-github-actions@master
      with: 
        command: init

    - uses: hashicorp/packer-github-actions@master
      with: 
        command: build
        arguments: -var-file=vars.pkrvars.hcl
        target: aws-ubuntu.pkr.hcl