name: ami validate action
on : push
jobs: 
  ami-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: Checkout

    - uses: hashicorp/packer-github-actions@master
      with: 
        command: validate
        arguments: -syntax-only
        target: aws-ubuntu.pkr.hcl